### 전체 분야 조회
GET http://localhost:8080/field
Accept: application/json

### 분야 ID 단일 조회
GET http://localhost:8080/field/1
Accept: application/json

### 분야 등록
POST http://localhost:8080/field
Content-Type: application/json

{
  "name": "사랑"
}