### 전체 시대 조회
GET http://localhost:8080/period
Accept: application/json

### 시대 ID 단일 조회
GET http://localhost:8080/period/13
Accept: application/json

### 시대 등록
POST http://localhost:8080/period
Content-Type: application/json

{
  "name": "AC 17세기"
}

### 시대 수정
PUT http://localhost:8080/period/11
Content-Type: application/json

{
  "name": "AD 21세기"
}