spring:
  application:
    name: Quote_Collection_Spring

  datasource:
    url: jdbc:mysql://localhost:3306/quotedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: quotecollection
    password: quotecollection

  jpa:
    generate-ddl: false          # 엔티티 바탕으로 테이블 자동 생성, 수정 등 하는 기능 끄기
    database: mysql              # 사용 데이터 베이스 mysql
    properties:
      hibernate:
        format_sql: true         # sql문을 들여쓰기 줄바꿈 등을하여 볼 수 있게
        highlight_sql: true      # sql문에 색상을 넣어 표시
        use_sql_comments: true   # 생성한 SQL에 어떤 작업에서 나온 SQL인지 파악하는 데 도움이 되는 주석 추가

  jackson:
    deserialization:
      fail-on-null-for-primitives: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

server:
  port: 8080
